services:
  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb
    ports:
      - '127.0.0.1:27017:27017'

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  gateway:
    extends:
      file: docker-compose.yml
      service: gateway
    image: dedisalam/backend-gateway:latest
    ports:
      - '127.0.0.1:3000:3000'

  user-service:
    extends:
      file: docker-compose.yml
      service: user-service
    image: dedisalam/backend-user-service:latest

  notification-service:
    extends:
      file: docker-compose.yml
      service: notification-service
    image: dedisalam/backend-notification-service:latest

networks:
  backend_network:
    driver: bridge
  cloudflare:
    external: true

volumes:
  mongodb_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:
